config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'gossips#index'
  get '/welcome/:first_name', to: 'welcome#welcome_message'
  get '/team', to: 'team#presentation'
  get '/contact', to: 'contact#show_contacts'
  
  resources :gossips
  resources :users
  resources :cities, only: [:show]

  resources :gossips do
    resources :comments, only: [:new, :create, :index, :destroy]
  end
  post '/gossips/:id/comments', to: "comments#create", as:"gossips_comment_create"
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes, only: [:new, :create, :destroy]
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users
  validates :city_name,
    presence: true,
    length: { in: 1..40, message: "Entre un nom de ville correct stp !"},
    format: {with: /[a-zA-Z]+(?:[\s-][a-zA-Z]+)*/, message: "Entre un nom de ville correct stp !"}

  validates :zip_code,
  presence: true,
  uniqueness: true
  # format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "Entre un code postal français stp !" }

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :author, class_name: "User"

  validates :content,
    presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord

  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :authors, foreign_key: 'author_id', class_name: "User"
  has_many :comments
  has_many :likes, dependent: :destroy

  validates :title,
    presence: true
    # length: { in: 3..14, message: "Ton potin doit être compris entre 3 et 14 caractères" }

  validates :content,
    presence: true

  def is_liked_by?(user)
    self.likes.map(&:liker_id).include?(user.id)
  end

  def get_like_by_user(liker)
    self.likes.find_by! liker_id: liker.id
  end

 end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip 
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :gossip
  belongs_to :liker, class_name: "User"

end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :city, optional: true
  has_many :gossips
  
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  has_many :comments, foreign_key: 'author_id', class_name: "Comment"

  has_many :likes, foreign_key: 'liker_id', class_name: "Like", dependent: :destroy

  

  validates :first_name,
    presence: true
    # length: { in: 3..14 },
    # format: {with: /[a-z ,.'-]+/i}

  validates :last_name,
    presence: true
    # length: { in: 3..25 },
    # format: {with: /[a-z ,.'-]+/i}

  validates :description,
    presence: true
    # length: { minimum: 140 }

  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Entre une adresse mail correcte stp !" }

  validates :age,
    presence: true
    # format: { with: /([1-9][8-9])/ }

    def remember(remember_token)
      remember_digest = BCrypt::Password.create(remember_token)
      self.update(remember_digest: remember_digest)
    end
    
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user

  def index
      @gossips = Gossip.all
      # @like = Like.new
      # @likes = Like.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @user = Gossip.find(params[:id]).user

    @gossips_comments = Gossip.find(params[:id]).comments

    # @comment = Comment.new(comment_params)
  #   @comment.author_id = 11
  #   @comment.gossip_id = Gossip.find(params[:id]).id

  #   if @comment.save
  #     redirect_to gossip_path
  #   else
  #     render :show
  #   end
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    @gossip.user_id = current_user.id
    if @gossip.save
      redirect_to gossips_path
    else
      render :new
    end
  end



  def edit
    @gossip = Gossip.find(params[:id])
    if current_user.id == @gossip.user.id
    else
    redirect_to gossips_path
    end
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end


  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
   User.find_by(id: session[:user_id])
  end

  def log_in(user)
   session[:user_id] = user.id
  end

  def is_logged_in?
    if session[:user_id] != nil
      true
    else
      false
    end
  end

  def current_user_liked_that?(gossip)
    gossip.is_liked_by?(current_user)
  end

  def get_like_of_current_user(gossip)
    gossip.get_like_by_user(current_user)
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<h1 class="jumbotron text-center mb-5 mt-5">Modifier le potin n°<%=@gossip.id%></h1>

<%= form_for @gossip, :html => {:class => "mt-5 form-signin text-center mx-auto user_form mb-5"} do |f|%>

  <div class="form-group text-left">
  <label>Titre</label>
    <%= f.text_field :title, class:"form-control", placeholder:"Titre" %>
  </div>

  <div class="form-group text-left">
    <label>Potin</label>
    <%= f.text_area :content, class:"form-control", placeholder:"Potin"%>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-lg btn-primary btn-block">Modifier le gossip</button>
  </div>

  <%= hidden_field_tag "gossip[user_id]", @user_id %>
  <% end %>

app/views/gossips/index.html.erb
<div class="container">

  <div class="welcome mb-5 mt-5">
    <div class="jumbotron text-center">
      <h1 class="display-1">The Gossip Project</h1>
      <div class="row">
      <h4> Bienvenue sur The Gossip Project, un site où vous pouvez raconter vos potins en gardant votre anonymat. Soyez cools quand-même !</h4>
    </div>
    <p class="h3 mt-4"><%= link_to "Créer un potin", new_gossip_path, class: "btn btn-dark mt-3" %></p>
    <a href="https://en.wikipedia.org/wiki/Gossip"><img src="https://images.vexels.com/media/users/3/157869/isolated/preview/13916a3fd62c9de9a2fdb623b38c0d1a-bare-teeth-open-mouth-icon-by-vexels.png" alt="The Gossip Project" width="100"></a>
  </div>

<h2>Bienvenue sur ta session <%= current_user.first_name %> <%= current_user.last_name %> !</h2>

<h3 class="mt-4">Voici tous les potins :</h3>

</div>

<div class="card-deck">
  <% @gossips.sort.each do |gossip| %>
    <div class="col-md-3 col-sm-4">
      <div class="card border-dark mb-3 mx-auto " style="max-width: 20rem;">
        <div class="card-header d-flex justify-content-between">
          <a href="<%=gossip_path(gossip.id)%>"> Gossip n°<%= gossip.id %></a>
          <% if current_user_liked_that?(gossip) %>
            <% like_id = get_like_of_current_user(gossip).id %>
            <a href="<%=like_path(like_id) %>" method="DELETE" ><img width="25" src="https://image.flaticon.com/icons/svg/535/535183.svg"/></a>
          <% else %>
            <a href="<%=likes_path%>" method="POST" ><img width="25" src="https://image.flaticon.com/icons/svg/1000/1000621.svg"/></a>
          <% end %>
        </div>
        <div class="card-body">
          <h4 class="card-title"><%= gossip.title %></h4>
          <p class="card-text"><%= gossip.user.first_name %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

</div>

app/views/gossips/new.html.erb
<h1 class="jumbotron text-center mb-5 mt-5">Ajoute un potin !</h1>

<% if @gossip.errors.any? %>
    <div class="alert alert-warning alert_message mx-auto" role="alert">
      <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>

<%= form_for @gossip, :html => {:class => "mt-5 form-signin text-center mx-auto user_form mb-5"} do |f|%>

  <div class="form-group">
    <%= f.text_field :title, class:"form-control", placeholder:"Titre" %>
  </div>
  <div class="form-group">
    <%= f.text_area :content, class:"form-control", placeholder:"Contenu" %>
  </div>

  <div class="form-group">
    <button type="submit" class="btn btn-lg btn-primary btn-block">Créer le potin</button>
  </div>

  <% end %>

app/views/gossips/show.html.erb
<div class="container justify-content-center">


<div class="jumbotron text-center">
  <h1 class="display-3 mt-5">Potin n°<%= params[:id]%></h1>
  <p class="h3"><%= @gossip.title %></p>

  <p class="h4"><%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@user.id)%>
  <p class="h6"><%= link_to "de #{@user.city.city_name}", city_path(@user.city.id)%>
  
  <hr class="my-4">

  <blockquote class="blockquote ">
  <p class="h4"><%= @gossip.content %></p>
  </blockquote>

  <% if current_user.id == @gossip.user_id%>
  <p class="lead">
    <%= link_to "Modifier le potin", edit_gossip_path(@gossip.id), class: "btn btn-warning mt-3 mb-3"%>
    <%= link_to "Supprimer le potin", gossip_path, method: :delete, class: "btn btn-danger mt-3 mb-3"%>
  </p>
   <% else %>
   <% end %>
  
</div>

<div>
<form action= <%= gossips_comment_create_path %> method="POST">
  <div class="form-group">
  <label for="exampleInputEmail1">Ajouter un commentaire</label>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" class="form-control mb-3" id="content" name="content" placeholder="Entre ton commentaire...">
  <input type="hidden" id="gossip_id" value="@id">
  <input type="submit" value="Ajouter" class="btn btn-primary">
  </div>
</form>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Auteur</th>
      <th scope="col">Commentaire</th>
    </tr>
  </thead>
<% @gossips_comments.each do |comment| %>

    <tr class="table-light">
      <th scope="row"><%= comment.author.first_name%></th>
      <td><%= comment.content %></td>
    </tr>
  </tbody>
<% end %>
</table> 
</div>